### ISSUE TITLE
BaseElementObject not extending Element problematic for sorting

### ISSUE THREAD

**Issue by michalkleiner** [dynamic/silverstripe-elemental-blocks#70]
Hi,

I came across an ordering issue today. I was able to narrow it down to the problem in the orderablerows gridfield extension, however, the background could affect other things as well. The main issue is that BaseElementObject doesn't extend BaseElement and some code in the elemental module expect the base class (the one directly extending DataObject) to be the BaseElement class from elemental module.

Is there a reason why you created your BaseElementObject class instead of using BaseElement class or extending it?

Cheers
Michal

**Comment by muskie9** [comment]
Hi @michalkleiner,

I think the way this is setup is the Elements in the module extend BaseElement but objects a particular Element may manage extend BaseElementObject. An example would be ElementAccordion is the element that manages the AccordionPanel DataObjects. It would be as if we were declaring the managed object, but have just created a base class that many will extend from to prevent having to redeclare common fields. This is similar to how a traditional Page would manage related DataObjects, but rather than a page, it's an element doing the managing.

@jsirish does this sound correct?

In any case, we should still dig into the issue and resolve the bug related to sorting as that's a feature users will expect.

**Comment by jsirish** [comment]
we think this was an issue with gridfieldextensions, closing for now
