### ISSUE TITLE
Quick Add New doesn't seem to be working in all cases

### ISSUE THREAD

**Issue by korthjp17** [dynamic/silverstripe-elemental-blocks#72]
@ashautumn added a form element to one page but couldn't find it in the link existing to put it on another page.

**Comment by muskie9** [comment]
Based on how the blocks work now, they can't be shared unless the setting "Globally Available" is checked. This is part of the virtual element module so when it's on another page it's only a virtual instance of it, not the main instance.

This may work for now if it doesn't hinder block functionality, otherwise removing the link existing is probably the better solution to avoid confusion at this point.

**Comment by muskie9** [comment]
closing in favor of #73
